env:
  es6: true
  es2020: true
  jest/globals: true
extends:
  # I want to know the best practices for the settings here.
  # I don't know it, but this so many extends are enough to make it feel non-exemplary.
  - eslint:recommended
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - prettier
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
  - prettier
root: true
rules:
  '@typescript-eslint/ban-ts-ignore':
    - 'warn'
  '@typescript-eslint/explicit-function-return-type':
    - 'off'
  import/extensions:
    - error
    - ignorePackages
    - ts: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*.config.?s'
        - '**/*.spec.?s'
settings:
  import/resolver:
    node:
      extensions:
        - .ts
      path:
        - src
